# Generated by Django 5.2.7 on 2025-11-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarsApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("icone", models.CharField(max_length=100)),
                ("descricao", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RankingLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="CarsApp.rankingitem",
                    ),
                ),
            ],
        ),
    ]
